import type { Metadata } from "next";
import {Noto_Serif_Bengali} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
const notoSerifBangli = Noto_Serif_Bengali({
  subsets: ["latin","bengali"],
});



export const metadata: Metadata = {
  title: "Bangla News 24",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`${notoSerifBangli.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header></Header>
        {children}
        
        </body>
    </html>
  );
}
